all:
	tclsh acplt_build.tcl trunk

trunk:
	tclsh acplt_build.tcl trunk

clean:
	rm acplt.build -rf
	rm acplt -rf
	rm acplt_build.log

source:
	tclsh acplt_build.tcl trunk source

release:
	tclsh acplt_build.tcl trunk release

