
/******************************************************************************
*
*   FILE
*   ----
*   SubscriptionResult.c
*
*   History
*   -------
*   2017-10-25   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_simpleExperimentDataArchiver
#define OV_COMPILE_LIBRARY_simpleExperimentDataArchiver
#endif


#include "simpleExperimentDataArchiver.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(simpleExperimentDataArchiver_SubscriptionResult)
OV_IMPL_UNLINK(simpleExperimentDataArchiver_SubscriptionResult)
OV_IMPL_GETACCESS(simpleExperimentDataArchiver_SubscriptionResult)

