
/******************************************************************************
*
*   FILE
*   ----
*   writer.c
*
*   History
*   -------
*   2018-01-12   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_simpleExperimentDataArchiver
#define OV_COMPILE_LIBRARY_simpleExperimentDataArchiver
#endif


#include "simpleExperimentDataArchiver.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_BOOL simpleExperimentDataArchiver_writer_start_get(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj
) {
    return pobj->v_start;
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_start_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_BOOL  value
) {
    pobj->v_start = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_BOOL simpleExperimentDataArchiver_writer_stop_get(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj
) {
    return pobj->v_stop;
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_stop_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_BOOL  value
) {
    pobj->v_stop = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_BOOL simpleExperimentDataArchiver_writer_reset_get(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj
) {
    return pobj->v_reset;
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_reset_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_BOOL  value
) {
    pobj->v_reset = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_UINT simpleExperimentDataArchiver_writer_state_get(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj
) {
    return pobj->v_state;
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_state_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_UINT  value
) {
    pobj->v_state = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_stateName_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_stateName,value);
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_errorMsg_set(
    OV_INSTPTR_simpleExperimentDataArchiver_writer          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_errorMsg,value);
}

OV_DLLFNCEXPORT OV_RESULT simpleExperimentDataArchiver_writer_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_simpleExperimentDataArchiver_writer pinst = Ov_StaticPtrCast(simpleExperimentDataArchiver_writer, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void simpleExperimentDataArchiver_writer_destructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_simpleExperimentDataArchiver_writer pinst = Ov_StaticPtrCast(simpleExperimentDataArchiver_writer, pobj);

    /* do what */

    /* destroy object */
    fb_functionblock_destructor(pobj);

    return;
}

OV_DLLFNCEXPORT void simpleExperimentDataArchiver_writer_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_simpleExperimentDataArchiver_writer pinst = Ov_StaticPtrCast(simpleExperimentDataArchiver_writer, pfb);

    return;
}

