
/******************************************************************************
*
*   FILE
*   ----
*   CreateSubModelService.c
*
*   History
*   -------
*   2017-10-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_subModelAdministration
#define OV_COMPILE_LIBRARY_subModelAdministration
#endif


#include "subModelAdministration.h"
#include "libov/ov_macros.h"
#include "helper.h"


OV_DLLFNCEXPORT OV_RESULT subModelAdministration_CreateSubModelService_CallMethod(      
  OV_INSTPTR_services_Service pobj,       
  OV_UINT numberofInputArgs,       
  const void **packedInputArgList,       
  OV_UINT numberofOutputArgs,      
  void **packedOutputArgList,
  OV_UINT *typeArray       
) {
    /*    
    *   local variables
    */
	OV_UINT result = 0;
	OV_INSTPTR_ov_object pParent = NULL;
	OV_INSTPTR_openaas_SubModel pSubModel = NULL;


	packedOutputArgList[0] = ov_database_malloc(sizeof(OV_UINT));
	typeArray[0] = OV_VT_UINT;
	*(OV_UINT*)packedOutputArgList[0] = OV_ERR_OK;


	if (*(OV_UINT*)packedInputArgList[1] != 0){
		*(OV_UINT*)packedOutputArgList[0] = OV_ERR_NOTIMPLEMENTED;
		return OV_ERR_OK;
	}

	pParent = ov_path_getobjectpointer(*(OV_STRING*)(packedInputArgList[0]), 2);
	if (pParent == NULL){
		*(OV_UINT*)packedOutputArgList[0] = OV_ERR_BADPATH;
		return OV_ERR_OK;
	}

	*(OV_UINT*)packedOutputArgList[0] = (OV_UINT)checkForSameAAS(Ov_PtrUpCast(ov_object, pobj), pParent);
	if (*(OV_UINT*)packedOutputArgList[0] != OV_ERR_OK){
		return OV_ERR_OK;
	}

	result = Ov_CreateObject(openaas_SubModel, pSubModel, Ov_StaticPtrCast(ov_domain, pParent), *(OV_STRING*)(packedInputArgList[4]));
	if(Ov_Fail(result)){
		ov_logfile_error("Fatal: could not create SubModel object - reason: %s", ov_result_getresulttext(result));
		*(OV_UINT*)packedOutputArgList[0] = (OV_UINT)result;
		return OV_ERR_OK;
	}

	ov_string_setvalue(&pSubModel->v_ModelIdString, *(OV_STRING*)(packedInputArgList[2]));
	pSubModel->v_ModelIdType = *(OV_UINT*)packedInputArgList[3];
	pSubModel->v_Revision = *(OV_UINT*)packedInputArgList[5];
	pSubModel->v_Version = *(OV_UINT*)packedInputArgList[6];

    return OV_ERR_OK;
}

