
/******************************************************************************
*
*   FILE
*   ----
*   OVDataForAAS.c
*
*   History
*   -------
*   2017-01-26   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_ACCESS openAASDiscoveryServer_OVDataForAAS_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_openAASDiscoveryServer_OVDataForAAS pinst = Ov_StaticPtrCast(openAASDiscoveryServer_OVDataForAAS, pobj);

    return (OV_ACCESS)0;
}

