
/******************************************************************************
*
*   FILE
*   ----
*   WagoIPCCom.c
*
*   History
*   -------
*   2018-03-05   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_wagoIPClib
#define OV_COMPILE_LIBRARY_wagoIPClib
#endif


#include "wagoIPClib.h"
#include "libov/ov_macros.h"
#include "kbus.h"
#include "kbusl.h"


OV_DLLFNCEXPORT void wagoIPClib_WagoIPCCom_typemethod (
	OV_INSTPTR_ksbase_ComTask	this
) {
    /*    
    *   local variables
    */
	OV_INSTPTR_ov_domain pDomain = Ov_GetParent(ov_containment, this);
	OV_INSTPTR_wagoIPClib_WagoIPCManager pManager = Ov_DynamicPtrCast(wagoIPClib_WagoIPCManager, pDomain);
	OV_INSTPTR_kbuslib_MailBox pMB = NULL;
	OV_BOOL execute = FALSE;
	OV_BOOL writeBack = FALSE;

	struct kbus_info* pinfo;
	int res = 0;

	if(!pManager){
		this->v_actimode = 0;
		return;
	}

	pinfo = kbus_get_info();

	Ov_ForEachChildEx(ov_containment, pManager, pMB, kbuslib_MailBox){
		switch((enum kbuslib_MBState)(pMB->v_state)){
		case MB_errorState:
		case MB_idle:
		case MB_finished:
			break;
		default:
			execute = TRUE;
		}
		if(execute)
			break;
	}

	if(!execute) // nothing to do; reading the process image is a waste of time
		return;


	res = kbus_read_input_image();
	res |= kbus_read_output_image();
	//ov_logfile_debug("%s: read image", this->v_identifier);
	if(res){
		ov_logfile_error("%s: getting process image failed", this->v_identifier);
		return;
	}


	Ov_ForEachChildEx(ov_containment, pManager, pMB, kbuslib_MailBox){
		switch((enum kbuslib_MBState)(pMB->v_state)){
		case MB_errorState:
		case MB_idle:
		case MB_finished:
			break;
		default:
			//ov_logfile_debug("%s: execute read write", pMB->v_identifier);
			kbuslib_MailBox_readwrite(pMB, (OV_BYTE*)pinfo->image.inputs.data+pMB->v_ByteAddress,
					(OV_BYTE*)pinfo->image.outputs.data+pMB->v_ByteAddressOut, &writeBack);
		}
	}

	if(writeBack){
		//ov_logfile_debug("%s: start image write", this->v_identifier);
		res = kbus_write_output_image();
		//ov_logfile_debug("%s: end image write", this->v_identifier);
		if(res)
			ov_logfile_error("%s: writing process image failed", this->v_identifier);
			return;
	}

    return;
}

