/*
*   The Framework was generated by the ACPLT/OV Builder.
*
*   Builder version: 1.0.0
*   Date of file generation:  21-Nov-2001 (10:25:25)
*/

#ifndef OV_COMPILE_LIBRARY_tasklib
#define OV_COMPILE_LIBRARY_tasklib
#endif


#include "tasklib.h"
#include "libov/ov_macros.h"
#include "libov/ov_scheduler.h"
#include "libov/ov_time.h"


OV_DLLFNCEXPORT void tasklib_SchedulerTask_startup(
	OV_INSTPTR_ov_object 	pobj
) {
	ov_object_startup(pobj);

	tasklib_SchedulerTask_activate(Ov_StaticPtrCast(tasklib_Task, pobj));
}

OV_DLLFNCEXPORT void tasklib_SchedulerTask_shutdown(
	OV_INSTPTR_ov_object 	pobj
) {
	ov_scheduler_unregister(pobj);
	ov_object_shutdown(pobj);
}

OV_DLLFNCEXPORT void tasklib_SchedulerTask_activate(
             OV_INSTPTR_tasklib_Task          ptask
) {
	OV_TIME acttime;
	OV_INSTPTR_ov_object pobj;

	
	pobj = Ov_PtrUpCast(ov_object, ptask);
	ov_time_gettime(&acttime);
	switch (ptask->v_actimode) {
		case 0:
			ov_scheduler_unregister(pobj);
			break;
		case 1:
			ov_scheduler_register(pobj, tasklib_SchedulerTask_execute);
			ov_scheduler_setreleventtime(pobj, &ptask->v_cycletime);
			ov_time_add(&ptask->v_proctime, &acttime, &ptask->v_cycletime);
			break;
		case 2:
			ov_scheduler_register(pobj, tasklib_SchedulerTask_execute);
			ov_scheduler_setreleventtime(pobj, &ptask->v_cycletime);
			ov_time_gettime(&acttime);
			ov_time_add(&ptask->v_proctime, &acttime, &ptask->v_cycletime);
			break;
		case 3:
			ov_scheduler_register(pobj, tasklib_SchedulerTask_execute);
			ov_scheduler_setabseventtime(pobj, &ptask->v_alarmtime);
			ptask->v_proctime = ptask->v_alarmtime;
			break;
		case 4:
			ov_scheduler_register(pobj, tasklib_SchedulerTask_execute);
			ov_scheduler_setabseventtime(pobj, &ptask->v_alarmtime);
			ptask->v_proctime = ptask->v_alarmtime;
			break;
	}
}

OV_DLLFNCEXPORT void tasklib_SchedulerTask_execute(
	OV_INSTPTR_ov_object pobj
) {
	OV_INSTPTR_tasklib_Task		       	pchildtask;
	OV_VTBLPTR_tasklib_Task			pvtable;	
	OV_TIME acttime;
	OV_INSTPTR_tasklib_Task ptask;

	ptask = Ov_StaticPtrCast(tasklib_Task, pobj);
	ov_time_gettime(&acttime);

	switch (ptask->v_actimode) {
		case 0:
			ov_scheduler_unregister(pobj);
			break;
		case 1:
			ov_scheduler_setreleventtime(pobj, &ptask->v_cycletime);
			ov_time_add(&ptask->v_proctime, &acttime, &ptask->v_cycletime);
			break;
		case 2:
			if (ov_time_compare(&ptask->v_alarmtime, &acttime) <=0) {
				ptask->v_actimode = 0;
				ov_scheduler_unregister(pobj);
			}
			else {
				ov_scheduler_setreleventtime(pobj, &ptask->v_cycletime);
				ov_time_add(&ptask->v_proctime, &acttime, &ptask->v_cycletime);
			}
			break;
		case 3:
			ptask->v_actimode = 0;
			ov_scheduler_unregister(pobj);
			break;
		case 4:
			ptask->v_actimode = 1;
			ov_scheduler_setreleventtime(pobj, &ptask->v_cycletime);
			ov_time_add(&ptask->v_proctime, &acttime, &ptask->v_cycletime);
			break;
	}

	pchildtask = Ov_GetFirstChild(tasklib_tasklist, ptask);
	while (pchildtask) {
		if ( (pchildtask->v_actimode > 0) && (ov_time_compare(&pchildtask->v_proctime, &acttime) <=0) ) {
			Ov_GetVTablePtr(tasklib_Task, pvtable, pchildtask);
			pvtable->m_execute(Ov_PtrUpCast(ov_object, pchildtask));
			switch (pchildtask->v_actimode) {
				case 1:
					ov_time_add(&pchildtask->v_proctime, &acttime, &pchildtask->v_cycletime);
					break;
				case 2:
					if (ov_time_compare(&pchildtask->v_alarmtime, &acttime) <=0) 
						pchildtask->v_actimode = 0;
					else ov_time_add(&pchildtask->v_proctime, &acttime, &pchildtask->v_cycletime);
					break;
				case 3:
					pchildtask->v_actimode = 0;
					break;
				case 4:
					ov_time_add(&pchildtask->v_proctime, &acttime, &pchildtask->v_cycletime);
					pchildtask->v_actimode = 1;
					break;
			}
		}
		pchildtask = Ov_GetNextChild(tasklib_tasklist, pchildtask);
	}
}

