
/******************************************************************************
*
*   FILE
*   ----
*   getSCUinfo.c
*
*   History
*   -------
*   2015-10-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_SSChelper
#define OV_COMPILE_LIBRARY_SSChelper
#endif


#include "SSChelper.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"


OV_DLLFNCEXPORT void SSChelper_getSCUinfo_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_SSChelper_getSCUinfo pinst = Ov_StaticPtrCast(SSChelper_getSCUinfo, pfb);
    OV_INSTPTR_ov_object temp= NULL;
    OV_INSTPTR_fb_functionchart pCSU= NULL;
    OV_ANY tempvar;
    if(pinst->v_path!= NULL){
    	temp=ov_path_getobjectpointer(pinst->v_path,2);
    	if(Ov_CanCastTo(fb_functionchart,temp)){
    		pCSU=Ov_DynamicPtrCast(fb_functionchart,temp);
    		temp=NULL;
    		ov_memstack_lock();
    		fb_functionchart_getport(pCSU,"workState",&tempvar);
    		ov_string_setvalue(&(pinst->v_workingState),tempvar.value.valueunion.val_string);
    		fb_functionchart_getport(pCSU,"occupiedBy",&tempvar);
    		ov_string_setvalue(&(pinst->v_occupiedBy),tempvar.value.valueunion.val_string);
    		//fb_functionchart_getport(pCSU,"setPoint",&tempvar);
    		//if(tempvar.value.valueunion.val_single){
    		//pinst->v_SetPoint=tempvar.value.valueunion.val_single;}
    		//fb_functionchart_getport(pCSU,"error",&tempvar);
    		//if(tempvar.value.valueunion.val_bool){
    		//pinst->v_SetPoint=tempvar.value.valueunion.val_bool;}
    		ov_memstack_unlock();
    		return;
    	}

    }
    //Reset values
	ov_string_setvalue(&(pinst->v_workingState),NULL);
	ov_string_setvalue(&(pinst->v_occupiedBy),NULL);
    return;
}

