
/******************************************************************************
*
*   FILE
*   ----
*   Reference1.c
*
*   History
*   -------
*   2014-10-24   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec62541
#define OV_COMPILE_LIBRARY_iec62541
#endif


#include "iec62541.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(iec62541_Reference1)
OV_IMPL_UNLINK(iec62541_Reference1)
OV_IMPL_GETACCESS(iec62541_Reference1)

