
/******************************************************************************
*
*   FILE
*   ----
*   uaObjectTypeNode.c
*
*   History
*   -------
*   2014-10-24   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec62541
#define OV_COMPILE_LIBRARY_iec62541
#endif


#include "iec62541.h"
#include "libov/ov_macros.h"


