
/******************************************************************************
*
*   FILE
*   ----
*   uaQueryServiceImplementations.c
*
*   History
*   -------
*   2014-10-13   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec62541
#define OV_COMPILE_LIBRARY_iec62541
#endif


#include "iec62541.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void iec62541_uaQueryServiceImplementations_initImplementations() {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaQueryServiceImplementations_QueryFirst(
		UA_Server						*server,
		const UA_QueryFirstRequest		*request,
		UA_QueryFirstResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaQueryServiceImplementations_QueryNext(
		UA_Server						*server,
		const UA_QueryNextRequest		*request,
		UA_QueryNextResponse				*response
) {
    return;
}

