
/******************************************************************************
*
*   FILE
*   ----
*   uaSubscriptionServiceImplementations.c
*
*   History
*   -------
*   2014-10-13   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec62541
#define OV_COMPILE_LIBRARY_iec62541
#endif


#include "iec62541.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_initImplementations() {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_CreateSubscription(
		UA_Server						*server,
		const UA_CreateSubscriptionRequest		*request,
		UA_CreateSubscriptionResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_ModifySubscription(
		UA_Server						*server,
		const UA_ModifySubscriptionRequest		*request,
		UA_ModifySubscriptionResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_SetPublishingMode(
		UA_Server						*server,
		const UA_SetPublishingModeRequest		*request,
		UA_SetPublishingModeResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_Publish(
		UA_Server						*server,
		const UA_PublishRequest		*request,
		UA_PublishResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_Republish(
		UA_Server						*server,
		const UA_RepublishRequest		*request,
		UA_RepublishResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_TransferSubscriptions(
		UA_Server						*server,
		const UA_TransferSubscriptionsRequest		*request,
		UA_TransferSubscriptionsResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaSubscriptionServiceImplementations_DeleteSubscriptions(
		UA_Server						*server,
		const UA_DeleteSubscriptionsRequest		*request,
		UA_DeleteSubscriptionsResponse				*response
) {
    return;
}

