
/******************************************************************************
*
*   FILE
*   ----
*   uaViewServiceImplementations.c
*
*   History
*   -------
*   2014-10-13   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec62541
#define OV_COMPILE_LIBRARY_iec62541
#endif


#include "iec62541.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_initImplementations() {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_Browse(
		UA_Server						*server,
		const UA_BrowseRequest		*request,
		UA_BrowseResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_BrowseNext(
		UA_Server						*server,
		const UA_BrowseNextRequest		*request,
		UA_BrowseNextResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_TranslateBrowsePathsToNodeIds(
		UA_Server						*server,
		const UA_TranslateBrowsePathsToNodeIdsRequest		*request,
		UA_TranslateBrowsePathsToNodeIdsResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_RegisterNodes(
		UA_Server						*server,
		const UA_RegisterNodesRequest		*request,
		UA_RegisterNodesResponse				*response
) {
    return;
}

OV_DLLFNCEXPORT void iec62541_uaViewServiceImplementations_UnregisterNodes(
		UA_Server						*server,
		const UA_UnregisterNodesRequest		*request,
		UA_UnregisterNodesResponse				*response
) {
    return;
}

