/* WARNING: This is a generated file.
 * Any manual changes will be overwritten. */

#ifndef LIFECYCLEENTRY_H_
#define LIFECYCLEENTRY_H_


# include "open62541.h"




_UA_BEGIN_DECLS

#define UA_NSLIFECYCLEENTRYID_LCESTATUSCODE 3003
#define UA_NSLIFECYCLEENTRYID_LIFECYCLEENTRY 3002
#define UA_NSLIFECYCLEENTRYID_LIFECYCLEARCHIVETYPE 1002
#define UA_NSLIFECYCLEENTRYID_CREATELCE 7001
#define UA_NSLIFECYCLEENTRYID_CREATELCESIMPLE 7002
#define UA_NSLIFECYCLEENTRYID_DELETELCE 7003
#define UA_NSLIFECYCLEENTRYID_GETLASTLCES 7009
#define UA_NSLIFECYCLEENTRYID_GETLCE 7005
#define UA_NSLIFECYCLEENTRYID_GETLCESIMPLE 7006
#define UA_NSLIFECYCLEENTRYID_SETLCE 7007
#define UA_NSLIFECYCLEENTRYID_SETLCESIMPLE 7008

extern UA_StatusCode nodeset_lifeCycleEntry(UA_Server *server);

_UA_END_DECLS

#endif /* LIFECYCLEENTRY_H_ */
