PLATFORM = nt
ACPLTDIR = ../../../
PLT_DIR = $(ACPLTDIR)plt/
KS_DIR = $(ACPLTDIR)ks/
ONCRPC_DIR = ../../../../oncrpc/
LIBPLT = $(PLT_DIR)build/$(PLATFORM)/libplt.lib
LIBKS = $(KS_DIR)build/$(PLATFORM)/libks.lib
LIBKSCLN = $(KS_DIR)build/$(PLATFORM)/libkscln.lib
LIBONCRPC = $(ONCRPC_DIR)bin/oncrpc.lib

CXX = bcc32

CXX_FLAGS = -w -v -pc -wsig- -a8 -O2 -d -DNDEBUG -DPLT_USE_BUFFERED_STREAMS=1
CXX_EXTRA_FLAGS = -I./ -I$(KS_DIR)include -I$(PLT_DIR)include -I$(ONCRPC_DIR)
CXX_PLATFORM_FLAGS = -DPLT_SYSTEM_NT=1
CXX_LIBS = 

CXX_COMPILE = $(CXX) $(CXX_EXTRA_FLAGS) $(CXX_PLATFORM_FLAGS) $(CXX_FLAGS) -c
CXX_LINK = bcc32 

dbdump.exe:		dbdump.obj fnmatch.obj
	$(CXX_LINK) $^ $(LIBKSCLN) $(LIBKS) $(LIBPLT) $(LIBONCRPC)
	@tdstrp32 dbdump.exe

dbdump.obj:	dbdump.cpp dbdump.h dbdump_inst.h
	$(CXX_COMPILE) dbdump.cpp

fnmatch.obj:	fnmatch.c fnmatch.h
	$(CXX_COMPILE) fnmatch.c

clean:
	-@del -f dbdump.obj fnmatch.obj core dbdump