
/******************************************************************************
*
*   FILE
*   ----
*   setpointhandler.c
*
*   History
*   -------
*   2014-03-31   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_SSChelper
#define OV_COMPILE_LIBRARY_SSChelper
#endif


#include "SSChelper.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void SSChelper_setpointhandler_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_SSChelper_setpointhandler pinst = Ov_StaticPtrCast(SSChelper_setpointhandler, pfb);

if(pinst->v_userok && pinst->v_order &&  (ov_string_compare(pinst->v_order,"STARTD1")==OV_STRCMP_EQUAL ||
		ov_string_compare(pinst->v_order,"STARTD2")==OV_STRCMP_EQUAL||ov_string_compare(pinst->v_order,"SETSETPOINT")==OV_STRCMP_EQUAL||ov_string_compare(pinst->v_order,"SETPOINT")==OV_STRCMP_EQUAL)){
	if(pinst->v_param)
	{
		pinst->v_value=atof(pinst->v_param);
	}
	else
	{
		pinst->v_value = 0.0;
	}
}
    return;
}

