
/******************************************************************************
*
*   FILE
*   ----
*   modelmanager.c
*
*   History
*   -------
*   2016-12-22   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openaas
#define OV_COMPILE_LIBRARY_openaas
#endif


#include "openaas.h"
#include "libov/ov_macros.h"
#include "nodeset.h"
#include "ua_openaas_generated.h"
#include "openaas_helpers.h"

extern OV_INSTPTR_openaas_nodeStoreFunctions pNodeStoreFunctions;

void openaas_modelmanager_AASConvertListAdd(IdentificationType aasId, OV_STRING aasName){
	OV_INSTPTR_openaas_modelmanager pmodelmanager = NULL;
	AASConvertListType* tmpAASConvertList = NULL;
	pmodelmanager = Ov_StaticPtrCast(openaas_modelmanager, Ov_GetFirstChild(ov_instantiation, pclass_openaas_modelmanager));
	tmpAASConvertList = ov_database_malloc(sizeof(AASConvertListType)*(pmodelmanager->v_Container.AASConvertListSize+1));
	if (pmodelmanager->v_Container.AASConvertListSize != 0){
		for (OV_UINT i = 0; i < pmodelmanager->v_Container.AASConvertListSize; i++){
			tmpAASConvertList[i].AASId.IdType = (pmodelmanager->v_Container.AASConvertList)[i].AASId.IdType;
			tmpAASConvertList[i].AASId.IdSpec = NULL;
			tmpAASConvertList[i].AASPath = NULL;
			ov_string_setvalue(&(tmpAASConvertList[i].AASId.IdSpec), (pmodelmanager->v_Container.AASConvertList)[i].AASId.IdSpec);
			ov_string_setvalue(&(tmpAASConvertList[i].AASPath), (pmodelmanager->v_Container.AASConvertList)[i].AASPath);
		}
		for (OV_UINT i = 0; i < pmodelmanager->v_Container.AASConvertListSize; i++){
			ov_database_free(pmodelmanager->v_Container.AASConvertList[i].AASId.IdSpec);
			ov_database_free(pmodelmanager->v_Container.AASConvertList[i].AASPath);
		}
		ov_database_free(pmodelmanager->v_Container.AASConvertList);
		pmodelmanager->v_Container.AASConvertList = NULL;
	}
	tmpAASConvertList[pmodelmanager->v_Container.AASConvertListSize].AASId.IdSpec = NULL;
	ov_string_setvalue(&(tmpAASConvertList[pmodelmanager->v_Container.AASConvertListSize].AASId.IdSpec), aasId.IdSpec);
	tmpAASConvertList[pmodelmanager->v_Container.AASConvertListSize].AASId.IdType = aasId.IdType;
	OV_STRING tmpString = NULL;
	ov_string_setvalue(&tmpString, "/TechUnits/openAAS/AASFolder/");
	ov_string_append(&tmpString, aasName);
	tmpAASConvertList[pmodelmanager->v_Container.AASConvertListSize].AASPath = NULL;
	ov_string_setvalue(&(tmpAASConvertList[pmodelmanager->v_Container.AASConvertListSize].AASPath), tmpString);
	pmodelmanager->v_Container.AASConvertList = tmpAASConvertList;
	pmodelmanager->v_Container.AASConvertListSize += 1;

	// Get the pointer to object for send the Message
	OV_INSTPTR_ksapi_setVar psendAASMessage = NULL;
	Ov_ForEachChildEx(ov_instantiation, pclass_ksapi_setVar, psendAASMessage, ksapi_setVar){
		if(ov_string_compare(psendAASMessage->v_identifier, "SendAASMessage") == OV_STRCMP_EQUAL){
			break;
		}
	}

	ov_string_setvalue(&psendAASMessage->v_serverHost, pNodeStoreFunctions->v_IPAddressAASDiscoveryServer);
	ov_string_setvalue(&psendAASMessage->v_serverName, pNodeStoreFunctions->v_ManagerNameAASDiscoveryServer);
	ov_string_setvalue(&psendAASMessage->v_path, pNodeStoreFunctions->v_PathToAASDiscoveryServer);
	ov_string_append(&psendAASMessage->v_path, ".AddOVDataForAAS");

	psendAASMessage->v_varValue.value.vartype = OV_VT_STRING_VEC;
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.veclen = 4;
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.value = ov_database_malloc(4 * sizeof(OV_STRING));
	if(!psendAASMessage->v_varValue.value.valueunion.val_string_vec.value){
		return;
	}

	OV_STRING tmpHexString = NULL;
	ov_string_print(&tmpHexString, "%x", aasId.IdType);

	for (OV_UINT i = 0; i < ov_string_getlength(aasId.IdSpec); i++){
		OV_STRING tmpHexString2 = NULL;
		ov_string_print(&tmpHexString2, "%x", aasId.IdSpec[i]);
		ov_string_append(&tmpHexString, tmpHexString2);
	}
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[0] = NULL;
	ov_string_setvalue(&psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[0], tmpHexString);
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[1] = NULL;
	ov_string_setvalue(&psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[1], pNodeStoreFunctions->v_IPAddressServer);
	OV_ANY tmpServername;
	ov_vendortree_getservername(&tmpServername, NULL);
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[2] = NULL;
	ov_string_setvalue(&psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[2], tmpServername.value.valueunion.val_string);
	psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[3] = NULL;
	ov_string_setvalue(&psendAASMessage->v_varValue.value.valueunion.val_string_vec.value[3], "/TechUnits/AASFolder/ComCo");

	OV_INSTPTR_ksapi_KSApiCommon pKSApiCommon = Ov_StaticPtrCast(ksapi_KSApiCommon, psendAASMessage);
	ksapi_KSApiCommon_Submit_set(pKSApiCommon, FALSE);
	ksapi_KSApiCommon_Submit_set(pKSApiCommon, TRUE);
	return;
}

void openaas_modelmanager_AASConvertListDelete(IdentificationType aasId){
	OV_INSTPTR_openaas_modelmanager pmodelmanager = NULL;
	AASConvertListType* tmpAASConvertList = NULL;
	pmodelmanager = Ov_StaticPtrCast(openaas_modelmanager, Ov_GetFirstChild(ov_instantiation, pclass_openaas_modelmanager));
	if (pmodelmanager->v_Container.AASConvertListSize == 1){
		ov_database_free(pmodelmanager->v_Container.AASConvertList[0].AASId.IdSpec);
		ov_database_free(pmodelmanager->v_Container.AASConvertList[0].AASPath);
		ov_database_free(pmodelmanager->v_Container.AASConvertList);
		pmodelmanager->v_Container.AASConvertList = NULL;
		pmodelmanager->v_Container.AASConvertListSize = 0;
		return;
	}
	tmpAASConvertList = ov_database_malloc(sizeof(AASConvertListType)*(pmodelmanager->v_Container.AASConvertListSize-1));
	OV_UINT j = 0;
	for (OV_UINT i = 0; i < pmodelmanager->v_Container.AASConvertListSize; i++){
		if (IdentificationTypeEqual(&((pmodelmanager->v_Container.AASConvertList)[i].AASId), &aasId))
			continue;
		tmpAASConvertList[j].AASId.IdType = (pmodelmanager->v_Container.AASConvertList)[i].AASId.IdType;
		tmpAASConvertList[i].AASId.IdSpec = NULL;
		tmpAASConvertList[i].AASPath = NULL;
		ov_string_setvalue(&(tmpAASConvertList[j].AASId.IdSpec), (pmodelmanager->v_Container.AASConvertList)[i].AASId.IdSpec);
		ov_string_setvalue(&(tmpAASConvertList[j].AASPath), (pmodelmanager->v_Container.AASConvertList)[i].AASPath);
		j++;
	}
	for (OV_UINT i = 0; i < pmodelmanager->v_Container.AASConvertListSize; i++){
		ov_database_free(pmodelmanager->v_Container.AASConvertList[i].AASId.IdSpec);
		ov_database_free(pmodelmanager->v_Container.AASConvertList[i].AASPath);
	}
	ov_database_free(pmodelmanager->v_Container.AASConvertList);
	pmodelmanager->v_Container.AASConvertList = NULL;
	pmodelmanager->v_Container.AASConvertList = tmpAASConvertList;
	pmodelmanager->v_Container.AASConvertListSize -= 1;

	// Get the pointer to object for send the Message
	OV_INSTPTR_ksapi_setVar psendAASMessage = NULL;
	Ov_ForEachChildEx(ov_instantiation, pclass_ksapi_setVar, psendAASMessage, ksapi_setVar){
		if(ov_string_compare(psendAASMessage->v_identifier, "SendAASMessage") == OV_STRCMP_EQUAL){
			break;
		}
	}

	ov_string_setvalue(&psendAASMessage->v_serverHost, pNodeStoreFunctions->v_IPAddressAASDiscoveryServer);
	ov_string_setvalue(&psendAASMessage->v_serverName, pNodeStoreFunctions->v_ManagerNameAASDiscoveryServer);
	ov_string_setvalue(&psendAASMessage->v_path, pNodeStoreFunctions->v_PathToAASDiscoveryServer);
	ov_string_append(&psendAASMessage->v_path, ".DeleteOVDataForAAS");

	psendAASMessage->v_varValue.value.vartype = OV_VT_STRING;
	OV_STRING tmpHexString = NULL;
	ov_string_print(&tmpHexString, "%x", aasId.IdType);

	for (OV_UINT i = 0; i < ov_string_getlength(aasId.IdSpec); i++){
		OV_STRING tmpHexString2 = NULL;
		ov_string_print(&tmpHexString2, "%x", aasId.IdSpec[i]);
		ov_string_append(&tmpHexString, tmpHexString2);
	}
	psendAASMessage->v_varValue.value.valueunion.val_string = NULL;
	ov_string_setvalue(&psendAASMessage->v_varValue.value.valueunion.val_string, tmpHexString);

	OV_INSTPTR_ksapi_KSApiCommon pKSApiCommon = Ov_StaticPtrCast(ksapi_KSApiCommon, psendAASMessage);
	ksapi_KSApiCommon_Submit_set(pKSApiCommon, FALSE);
	ksapi_KSApiCommon_Submit_set(pKSApiCommon, TRUE);
	return;
}

OV_STRING openaas_modelmanager_AASConvertListGet(IdentificationType aasId){
	OV_INSTPTR_openaas_modelmanager pmodelmanager = NULL;
	pmodelmanager = Ov_StaticPtrCast(openaas_modelmanager, Ov_GetFirstChild(ov_instantiation, pclass_openaas_modelmanager));
	if (pmodelmanager->v_Container.AASConvertListSize == 0){
		return "";
	}
	for (OV_UINT i = 0; i < pmodelmanager->v_Container.AASConvertListSize; i++){
		if (IdentificationTypeEqual(&((pmodelmanager->v_Container.AASConvertList)[i].AASId), &aasId)){
			return (pmodelmanager->v_Container.AASConvertList)[i].AASPath;
		}
	}
	return "";
}



OV_DLLFNCEXPORT UA_NodeId openaas_modelmanager_getAASNodeId(IdentificationType aasId) {
    return UA_NODEID_STRING_ALLOC(pNodeStoreFunctions->v_NameSpaceIndexNodeStoreInterface, openaas_modelmanager_AASConvertListGet(aasId));;
}


OV_DLLFNCEXPORT AASStatusCode openaas_modelmanager_ovresultToAASStatusCode(OV_RESULT result) {
	switch(result){
	case OV_ERR_OK:
		return AASSTATUSCODE_GOOD;
	default:
		return AASSTATUSCODE_BADUNEXPECTEDERROR;
	}
}




OV_DLLFNCEXPORT OV_ACCESS openaas_modelmanager_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*
    *   local variables
    */
    return (OV_ACCESS)(OV_AC_WRITE | OV_AC_READ | OV_AC_LINKABLE | OV_AC_UNLINKABLE | OV_AC_DELETEABLE | OV_AC_RENAMEABLE);
}


OV_DLLFNCEXPORT OV_RESULT openaas_modelmanager_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*
    *   local variables
    */
    //OV_INSTPTR_openaas_modelmanager pinst = Ov_StaticPtrCast(openaas_modelmanager, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void openaas_modelmanager_destructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*
    *   local variables
    */
    //OV_INSTPTR_openaas_modelmanager pinst = Ov_StaticPtrCast(openaas_modelmanager, pobj);

    /* do what */

    /* destroy object */
    ov_object_destructor(pobj);

    return;
}



OV_DLLFNCEXPORT void openaas_modelmanager_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*
    *   local variables
    */
    //OV_INSTPTR_openaas_modelmanager pinst = Ov_StaticPtrCast(openaas_modelmanager, pobj);

    /* do what the base class does first */
    ov_object_startup(pobj);

    /* do what */

    // Add InformationModel & NodeStoreInterface & Reference to AASFolder
    UA_StatusCode ret = UA_STATUSCODE_GOOD;
    OV_INSTPTR_openaas_nodeStoreFunctions pNodeStoreFunctions = NULL;
    pNodeStoreFunctions = Ov_StaticPtrCast(openaas_nodeStoreFunctions, Ov_GetFirstChild(ov_instantiation, pclass_openaas_nodeStoreFunctions));
    ret = opcua_uaServer_addInformationModel(&pNodeStoreFunctions->v_NodeStoreInterface, "http://acplt.org/AAS/Ov", "/TechUnits/openAAS", nodeset_returnIndices, &pNodeStoreFunctions->v_NameSpaceIndexInformationModel, &pNodeStoreFunctions->v_NameSpaceIndexNodeStoreInterface, UA_OPENAAS, UA_OPENAAS_COUNT);
	if (ret != UA_STATUSCODE_GOOD){
		ov_logfile_error("openaas: Fatal: Couldn't add InformationModel");
	}

    return;
}

