
/******************************************************************************
*
*   FILE
*   ----
*   unregister.c
*
*   History
*   -------
*   2010-00-18   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_ksservtcp
#define OV_COMPILE_LIBRARY_ksservtcp
#endif


#include "ksservtcp.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"
#include "libov/ov_logfile.h"
#include <string.h>


OV_DLLFNCEXPORT OV_STRING ksservtcp_unregister_name_get(
    OV_INSTPTR_ksservtcp_unregister          pobj
) {
    return pobj->v_name;
}

OV_DLLFNCEXPORT OV_RESULT ksservtcp_unregister_name_set(
    OV_INSTPTR_ksservtcp_unregister          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_name,value);
}

OV_DLLFNCEXPORT OV_INT ksservtcp_unregister_version_get(
    OV_INSTPTR_ksservtcp_unregister          pobj
) {
    return pobj->v_version;
}

OV_DLLFNCEXPORT OV_RESULT ksservtcp_unregister_version_set(
    OV_INSTPTR_ksservtcp_unregister          pobj,
    const OV_INT  value
) {
    pobj->v_version = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_BOOL ksservtcp_unregister_process_get(
    OV_INSTPTR_ksservtcp_unregister          pobj
) {
    return pobj->v_process;
}

OV_DLLFNCEXPORT OV_RESULT ksservtcp_unregister_process_set(
    OV_INSTPTR_ksservtcp_unregister          pobj,
    const OV_BOOL  value
) {
  	 OV_INSTPTR_ov_domain sldomain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/servers",2);
  	 OV_INSTPTR_ksservtcp_serverlist psl = NULL;

    pobj->v_process = value;
    
    if(value == TRUE)
    {
		 if((pobj->v_name) && (pobj->v_version) && (sldomain))
		 {//all values are set
		 	psl = (OV_INSTPTR_ksservtcp_serverlist)Ov_SearchChild(ov_containment, sldomain, pobj->v_name);
			if(psl)
			{
				Ov_DeleteObject(psl);
				ksservtcp_unregister_res_set(pobj, 1);
				//~ ksservtcp_unregister_name_set(pobj, "");
				//~ ksservtcp_unregister_version_set(pobj, 0);
			}
			else
			{
				ov_logfile_error("unregister:	entry not found");
				ksservtcp_unregister_res_set(pobj, -2);
				return OV_ERR_GENERIC;
			}
		}
		else
		{
			ov_logfile_error("unregister: not all values set.");
			ksservtcp_unregister_res_set(pobj, -1);
			return OV_ERR_GENERIC;
		}
	}
			
	 pobj->v_process = FALSE;
    
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_INT ksservtcp_unregister_res_get(
    OV_INSTPTR_ksservtcp_unregister          pobj
) {
    return pobj->v_res;
}

OV_DLLFNCEXPORT OV_RESULT ksservtcp_unregister_res_set(
    OV_INSTPTR_ksservtcp_unregister          pobj,
    const OV_INT  value
) {
    pobj->v_res = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void ksservtcp_unregister_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */

    /* do what the base class does first */
    ov_object_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void ksservtcp_unregister_shutdown(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */

    /* do what */

    /* set the object's state to "shut down" */
    ov_object_shutdown(pobj);

    return;
}

