
CC = gcc -mno-cygwin
AR = ar

# If you want to use the new multithreaded server feature uncomment this line
#MT = -DMULTITHREAD

# If the rpc include directory is not included in the standard path
# you have to give the path to it here.
RPCINCLUDEPATH = ..

# If the rpc library is not included in the standard lib path
# you have to give the path to it here.
RPCLIBPATH = ..\bin\\

OBJS =		COUNT.o \
		COU_SVC.o \
		COU_XDR.o

RPCGEN = 	..\bin\rpcgen.exe

all: COU_SVC.EXE DO_COU.EXE

clean:
	cmd /c del *.o *.EXE COU.H COU_CLNT.* COU_SVC.* COU_XDR.*

COU_SVC.EXE: 	COUNT.o \
		COU_SVC.o \
		COU_XDR.o \
		$(RPCLIBPATH)oncrpc.dll
	$(CC) $(conlflags) $(ldebug) -o COU_svc.exe COUNT.o COU_XDR.o COU_SVC.o $(conlibsdll) $(RPCLIBPATH)oncrpc.dll
	cmd /c copy COU_svc.exe ..\bin

DO_COU.EXE: 	COU_CLNT.o \
		COU_XDR.o \
		DO_COU.o \
		$(RPCLIBPATH)oncrpc.dll
	$(CC) $(conlflags) $(ldebug) -o DO_COU.exe COU_XDR.o COU_CLNT.o DO_COU.o $(conlibsdll) $(RPCLIBPATH)oncrpc.dll
	cmd /c copy DO_COU.exe ..\bin

.c.o:
	$(CC) -c -I$(RPCINCLUDEPATH) $(MT) $(cdebug) $(cflags) $(cvarsdll) $*.c

COUNT.o: COUNT.c COU.H
COU_SVC.o: COU_SVC.c
COU_CLNT.o: COU_CLNT.c
DO_COU.o: DO_COU.c COU.H
COU_XDR.o: COU_XDR.c

COU_XDR.C:	COU.X
	$(RPCGEN) COU.X

COU.H:	COU.X
	$(RPCGEN) COU.X

COU_CLNT.C:	COU.X
	$(RPCGEN) COU.X

COU_SVC.C:	COU.X
	$(RPCGEN) COU.X
