
/******************************************************************************
*
*   FILE
*   ----
*   interface.c
*
*   History
*   -------
*   2017-10-11   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_subModelAdministrationOPCUAInterface
#define OV_COMPILE_LIBRARY_subModelAdministrationOPCUAInterface
#endif


#include "subModelAdministrationOPCUAInterface.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT UA_NodestoreInterface* subModelAdministrationOPCUAInterface_interface_ovNodeStoreInterfaceSubModelAdministrationNew(void);
typedef void SERVICES_FNC_OVNODESTOREINTERFACESUBMODELADMINISTRATIONDELETE(UA_NodestoreInterface * nsi) {

    return (UA_NodestoreInterface*)0;
}

OV_DLLFNCEXPORT void subModelAdministrationOPCUAInterface_interface_ovNodeStoreInterfaceSubModelAdministrationDelete(UA_NodestoreInterface * nsi) {

    return;
}

OV_DLLFNCEXPORT OV_RESULT subModelAdministrationOPCUAInterface_interface_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_subModelAdministrationOPCUAInterface_interface pinst = Ov_StaticPtrCast(subModelAdministrationOPCUAInterface_interface, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void subModelAdministrationOPCUAInterface_interface_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_subModelAdministrationOPCUAInterface_interface pinst = Ov_StaticPtrCast(subModelAdministrationOPCUAInterface_interface, pobj);

    /* do what the base class does first */
    ov_object_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void subModelAdministrationOPCUAInterface_interface_destructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_subModelAdministrationOPCUAInterface_interface pinst = Ov_StaticPtrCast(subModelAdministrationOPCUAInterface_interface, pobj);

    /* do what */

    /* destroy object */
    ov_object_destructor(pobj);

    return;
}

OV_DLLFNCEXPORT OV_ACCESS subModelAdministrationOPCUAInterface_interface_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_subModelAdministrationOPCUAInterface_interface pinst = Ov_StaticPtrCast(subModelAdministrationOPCUAInterface_interface, pobj);

    return (OV_ACCESS)0;
}

