
/******************************************************************************
*
*   FILE
*   ----
*   getSCUinfo.c
*
*   History
*   -------
*   2015-10-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_SSChelper
#define OV_COMPILE_LIBRARY_SSChelper
#endif


#include "SSChelper.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"


OV_DLLFNCEXPORT void SSChelper_getSCUinfo_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_SSChelper_getSCUinfo pinst = Ov_StaticPtrCast(SSChelper_getSCUinfo, pfb);
    OV_INSTPTR_ov_object temp= NULL;
    OV_INSTPTR_fb_functionchart pCSU= NULL;
 OV_ANY tempvar;
    if(pinst->v_Path!= NULL){
    	temp=ov_path_getobjectpointer(pinst->v_Path,2);
    	if(Ov_CanCastTo(fb_functionchart,temp)){
    		pCSU=Ov_DynamicPtrCast(fb_functionchart,temp);
    		temp=NULL;
    		fb_functionchart_getport(pCSU,"workingState",&tempvar);
    		if(tempvar.value.valueunion.val_string){
    		ov_string_setvalue(&(pinst->v_workingState),tempvar.value.valueunion.val_string);}
    		fb_functionchart_getport(pCSU,"allocatedBy",&tempvar);
    		if(tempvar.value.valueunion.val_string){
    		ov_string_setvalue(&(pinst->v_allocatedBy),tempvar.value.valueunion.val_string);}
    		fb_functionchart_getport(pCSU,"setPoint",&tempvar);
    		if(tempvar.value.valueunion.val_single){
    		pinst->v_SetPoint=tempvar.value.valueunion.val_single;}
    		fb_functionchart_getport(pCSU,"error",&tempvar);
    		if(tempvar.value.valueunion.val_bool){
    		pinst->v_SetPoint=tempvar.value.valueunion.val_bool;}


    	}

    }
    return;
}

