#
# Makefile.vms -- you'll know by now...
#

all:
	@write sys$$output "Usage:"
	@write sys$$output "  make clean            -- remove all objects, executables, libs, etc."
	@write sys$$output "  make openvms.all      -- build libraries and examples"
	@write sys$$output "  make openvms.acplt    -- build the libraries only"

clean:
	@write sys$$output "-------------------------------------------------------------"
	@write sys$$output "Cleaning up......"
	@write sys$$output "-------------------------------------------------------------"
	@\@vmsmaker [.plt.build.openvms] $(MAKE) clean
	@\@vmsmaker [.ks.build.openvms] $(MAKE) clean

openvms.acplt:
	@write sys$$output "-------------------------------------------------------------"
	@write sys$$output "Building the libPLT..."
	@write sys$$output "-------------------------------------------------------------"
	@\@vmsmaker [.plt.build.openvms] $(MAKE)
	@write sys$$output "-------------------------------------------------------------"
	@write sys$$output "Building the libKS..."
	@write sys$$output "-------------------------------------------------------------"
	@\@vmsmaker [.ks.build.openvms] $(MAKE)

openvms.all:	openvms.acplt
	@write sys$$output "-------------------------------------------------------------"
	@write sys$$output "Building examples..."
	@write sys$$output "-------------------------------------------------------------"
	@\@vmsmaker [.ks.build.openvms] $(MAKE) examples

