
/******************************************************************************
*
*   FILE
*   ----
*   MsgComponent.c
*
*   History
*   -------
*   2010-03-26   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_msgreceiver
#define OV_COMPILE_LIBRARY_msgreceiver
#endif


#include "msgreceiver.h"
#include "receiverconfig.h"

/*OV_DLLFNCEXPORT OV_RESULT msgreceiver_Receiver_sendCMD_set(
    OV_INSTPTR_msgreceiver_Receiver         pobj,
    const OV_INT  value
) {
	OV_INSTPTR_msgsys_MsgComponent msgsys = NULL;
	OV_INSTPTR_msgsys_Message	message = NULL;
	OV_INSTPTR_ov_domain	msgsys_domain = NULL;

	 msgsys_domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/Receiver", 2);
	  ov_logfile_debug("Creating Object 'Message'");
	  	  if(!msgsys_domain)
	    {
	      ov_logfile_error("Fatal: Coudnt find Application-Domain '/TechUnits/'! - Fatal Error");
	    }

	  if(!Ov_OK((Ov_CreateObject(msgsys_Message, message, msgsys_domain, MESSAGECONTAINER))))
	    {
	      ov_logfile_error("Fatal: Couldnt create Object 'Message'");
	    } 
	  else 
	    {
	      ov_logfile_debug("Done.");
	    }

	msgsys = (OV_INSTPTR_msgsys_MsgComponent) ov_path_getobjectpointer("/TechUnits/MsgSys", 2);
	msgsys_MsgComponent_sendMessage(msgsys,message);
	ov_logfile_debug("Nachricht gesendet!");
	Ov_DeleteObject(message);
	pobj->v_sendCMD = value;
    return OV_ERR_OK;
}*/

OV_DLLFNCEXPORT OV_RESULT msgreceiver_Receiver_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
	OV_INSTPTR_msgreceiver_Receiver this = Ov_StaticPtrCast(msgreceiver_Receiver, pobj);
	OV_RESULT result = fb_functionblock_constructor(pobj);
	OV_VTBLPTR_msgreceiver_Receiver thisVtable = NULL;
	OV_INSTPTR_msgsys_MsgComponent msgsys = NULL;

    /* do what the base class does first */


    if(Ov_Fail(result))
        return result;
			this->v_iexreq = TRUE;
			this->v_cyctime = RECEIVERCYCTIME;
			this->v_actimode = TRUE;

    /* do what */
	msgsys = (OV_INSTPTR_msgsys_MsgComponent) ov_path_getobjectpointer("/TechUnits/MsgSys", 2);
	Ov_GetVTablePtr(msgreceiver_Receiver, thisVtable, this);
	msgsys_MsgComponent_registerService(msgsys,"Receiver","/TechUnits/Receiver/Inbox",thisVtable->m_arrivalMethod);

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void msgreceiver_Receiver_retMethod(
						   OV_INSTPTR_ov_object pobj,
						   OV_INSTPTR_ov_object message,
						   OV_STRING errorstring,
						   OV_INT errorcode
){
	OV_INSTPTR_msgsys_Message msg = Ov_StaticPtrCast(msgsys_Message, message);
	ov_logfile_debug("Receiver: retMethod: Called with %d/%s for Message: %s with ID: %lu !",errorcode,errorstring,msg->v_identifier,msg->v_msgID);

	return;
}

OV_DLLFNCEXPORT void msgreceiver_Receiver_arrivalMethod(
						   OV_INSTPTR_ov_object pobj,
						   OV_INSTPTR_ov_object message
){
	OV_INSTPTR_msgsys_Message msg = Ov_StaticPtrCast(msgsys_Message, message);
	OV_INSTPTR_msgreceiver_Receiver this = (OV_INSTPTR_msgreceiver_Receiver)ov_path_getobjectpointer("/TechUnits/Receiver",2);
	OV_INSTPTR_msgsys_MsgComponent msgsys = NULL;
	OV_INSTPTR_msgsys_Message	message2 = NULL;
	OV_INSTPTR_ov_domain	msgsys_domain = NULL;
	OV_VTBLPTR_msgreceiver_Receiver thisVtable = NULL;
	OV_RESULT result = 0;

	ov_logfile_debug("Receiver: arrivalMethod: Called for Message: %s with ID: %lu !",msg->v_identifier,msg->v_msgID);

	ov_logfile_debug("Receiver: arrivalMethod: Creating Object 'Message'");
	 msgsys_domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/Receiver/Outbox", 2);
	 if(!msgsys_domain){
		ov_logfile_error("Receiver: arrivalMethod: Fatal: Coudnt find Application-Domain '/TechUnits/Receiver/OutBox'! - Fatal Error");
		return;
	 }

	msgsys_CreateAnonymousMessage(msgsys_Message,message2,msgsys_domain,"OutgoingMessage",&result);
	if(!result){
		ov_logfile_error("Receiver: arrivalMethod: Fatal: Couldnt create Object 'Message'");
		return;
	} 
	else{
		ov_logfile_debug("Receiver: arrivalMethod: Done.");
	}
	
	//Rollentausch!
	msgsys_Message_senderAddress_set(message2,msg->v_receiverAddress);
	msgsys_Message_senderName_set(message2,msg->v_receiverName);
	msgsys_Message_senderService_set(message2,msg->v_receiverService);
	msgsys_Message_receiverAddress_set(message2,msg->v_senderAddress);
	msgsys_Message_receiverName_set(message2,msg->v_senderName);
	msgsys_Message_receiverService_set(message2,msg->v_senderService);
	msgsys_Message_msgDataType_set(message2,"STRING");
	msgsys_Message_msgType_set(message2,1);
	msgsys_Message_msgSTRING_set(message2,"I got your Message!");

	msgsys = (OV_INSTPTR_msgsys_MsgComponent) ov_path_getobjectpointer("/TechUnits/MsgSys", 2);
	Ov_GetVTablePtr(msgreceiver_Receiver, thisVtable, this);

	msgsys_MsgComponent_sendMessage(msgsys,message2,thisVtable->m_retMethod);
	ov_logfile_debug("Receiver: arrivalMethod: Message sent!");

	return;
}

OV_DLLFNCEXPORT void msgreceiver_Receiver_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
	//OV_INSTPTR_msgsys_MessageBox this = Ov_StaticPtrCast(msgsys_MessageBox, pfb);

	return;
}

