
/******************************************************************************
*
*   FILE
*   ----
*   linkObject.c
*
*   History
*   -------
*   2013-05-14   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_ksapi
#define OV_COMPILE_LIBRARY_ksapi
#endif


#include "ksapi.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void ksapi_linkObject_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_ksapi_linkObject pinst = Ov_StaticPtrCast(ksapi_linkObject, pobj);

    /* do what the base class does first */
    ksapi_KSApiCommon_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void ksapi_linkObject_shutdown(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_ksapi_linkObject pinst = Ov_StaticPtrCast(ksapi_linkObject, pobj);

    /* do what */

    /* set the object's state to "shut down" */
    ksapi_KSApiCommon_shutdown(pobj);

    return;
}

OV_DLLFNCEXPORT void ksapi_linkObject_submit(
    OV_INSTPTR_ksapi_linkObject          pobj
) {
    return;
}

OV_DLLFNCEXPORT void ksapi_linkObject_setandsubmit(
    OV_INSTPTR_ksapi_linkObject          pobj,
	OV_STRING 									serverHost,
	OV_STRING 									serverName,
	OV_STRING 									path,
	OV_STRING 									elementpath,
	OV_INT										position,
	OV_STRING									place
) {
    return;
}

