
/******************************************************************************
*
*   FILE
*   ----
*   LifeCycleEntry.c
*
*   History
*   -------
*   2016-12-16   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_lifeCycleEntry
#define OV_COMPILE_LIBRARY_lifeCycleEntry
#endif


#include "lifeCycleEntry.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_ACCESS lifeCycleEntry_LifeCycleEntry_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */

    return (OV_ACCESS)OV_AC_WRITE | OV_AC_READ | OV_AC_LINKABLE | OV_AC_UNLINKABLE | OV_AC_DELETEABLE | OV_AC_RENAMEABLE;
}


OV_DLLFNCEXPORT OV_RESULT lifeCycleEntry_LifeCycleEntry_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*
    *   local variables
    */
    OV_INSTPTR_lifeCycleEntry_LifeCycleEntry pinst = Ov_StaticPtrCast(lifeCycleEntry_LifeCycleEntry, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */
    pinst->v_Data.value.valueunion.val_int = 0;
    pinst->v_Data.value.vartype = OV_VT_INT;

    return OV_ERR_OK;
}

