
/******************************************************************************
*
*   FILE
*   ----
*   InstantiateTemplate.c
*
*   History
*   -------
*   2012-01-12   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_cshmi
#define OV_COMPILE_LIBRARY_cshmi
#endif


#include "cshmilib.h"

OV_DLLFNCEXPORT OV_RESULT cshmi_InstantiateTemplate_zindex_set(
    OV_INSTPTR_cshmi_InstantiateTemplate          pobj,
    const OV_UINT  value
) {
    pobj->v_zindex = value;
    return OV_ERR_OK;
}
