
/******************************************************************************
*
*   FILE
*   ----
*   MsgComponent.c
*
*   History
*   -------
*   2010-03-26   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_msgsys
#define OV_COMPILE_LIBRARY_msgsys
#endif


#include "msgsys.h"
#include "msgconfig.h"

/*OV_DLLFNCEXPORT OV_RESULT msgsys_Receiver_sendCMD_set(
    OV_INSTPTR_msgsys_Receiver         pobj,
    const OV_INT  value
) {
	OV_INSTPTR_msgsys_MsgComponent msgsys = NULL;
	OV_INSTPTR_msgsys_Message	message = NULL;
	OV_INSTPTR_ov_domain	msgsys_domain = NULL;

	 msgsys_domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/Receiver", 2);
	  ov_logfile_debug("Creating Object 'Message'");
	  	  if(!msgsys_domain)
	    {
	      ov_logfile_error("Fatal: Coudnt find Application-Domain '/TechUnits/'! - Fatal Error");
	    }

	  if(!Ov_OK((Ov_CreateObject(msgsys_Message, message, msgsys_domain, MESSAGECONTAINER))))
	    {
	      ov_logfile_error("Fatal: Couldnt create Object 'Message'");
	    } 
	  else 
	    {
	      ov_logfile_debug("Done.");
	    }

	msgsys = (OV_INSTPTR_msgsys_MsgComponent) ov_path_getobjectpointer("/TechUnits/MsgSys", 2);
	msgsys_MsgComponent_sendMessage(msgsys,message);
	ov_logfile_debug("Nachricht gesendet!");
	Ov_DeleteObject(message);
	pobj->v_sendCMD = value;
    return OV_ERR_OK;
}*/

OV_DLLFNCEXPORT OV_STRING msgsys_Msg2StringMessageBox_text_get(
    OV_INSTPTR_msgsys_Msg2StringMessageBox          pobj
) {
    return pobj->v_text;
}

OV_DLLFNCEXPORT OV_RESULT msgsys_Msg2StringMessageBox_text_set(
    OV_INSTPTR_msgsys_Msg2StringMessageBox          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_text,value);
}

OV_DLLFNCEXPORT OV_RESULT msgsys_Msg2StringMessageBox_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
	OV_INSTPTR_msgsys_Msg2StringMessageBox this = Ov_StaticPtrCast(msgsys_Msg2StringMessageBox, pobj);
	OV_RESULT result = fb_functionblock_constructor(pobj);
	//OV_VTBLPTR_msgsys_Msg2StringMessageBox thisVtable = NULL;
	//OV_INSTPTR_msgsys_MsgComponent msgsys = NULL;

    /* do what the base class does first */


    if(Ov_Fail(result))
        return result;
			this->v_iexreq = TRUE;
			this->v_cyctime = RECEIVERCYCTIME;
			this->v_actimode = TRUE;

    /* do what
	msgsys = (OV_INSTPTR_msgsys_MsgComponent) ov_path_getobjectpointer("/TechUnits/MsgSys", 2);
	Ov_GetVTablePtr(msgsys_Msg2StringMessageBox, thisVtable, this);
	msgsys_MsgComponent_registerService(msgsys,"Msg2StringMessageBox","/TechUnits/Msg2StringMessageBox/Inbox",thisVtable->m_arrivalMethod);
     */
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void msgsys_Msg2StringMessageBox_retMethod(
						   OV_INSTPTR_ov_object pobj,
						   OV_INSTPTR_ov_object message,
						   OV_STRING errorstring,
						   OV_INT errorcode
){
	OV_INSTPTR_msgsys_Message msg = Ov_StaticPtrCast(msgsys_Message, message);
	ov_logfile_debug("Msg2StringMessageBox: retMethod: Called with %d/%s for Message: %s with ID: %lu !",errorcode,errorstring,msg->v_identifier,msg->v_msgID);

	return;
}

OV_DLLFNCEXPORT void msgsys_Msg2StringMessageBox_arrivalMethodImpl(
						   OV_INSTPTR_msgsys_MessageBox pobj,
						   OV_INSTPTR_msgsys_Message message
){
	OV_INSTPTR_msgsys_Message msg = Ov_StaticPtrCast(msgsys_Message, message);
	OV_INSTPTR_msgsys_Msg2StringMessageBox pinst = (OV_INSTPTR_msgsys_Msg2StringMessageBox)pobj;


	ov_string_setvalue(&pinst->v_text, msgsys_Message_msgBody_get(msg));
	
	return;
}

OV_DLLFNCEXPORT void msgsys_Msg2StringMessageBox_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
	//OV_INSTPTR_msgsys_MessageBox this = Ov_StaticPtrCast(msgsys_MessageBox, pfb);

	return;
}

