
/******************************************************************************
*
*   FILE
*   ----
*   gpioOut.c
*
*   History
*   -------
*   2017-06-01   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_raspi
#define OV_COMPILE_LIBRARY_raspi
#endif


#include "raspi.h"
#include "libov/ov_macros.h"
#include <wiringPi.h>



OV_DLLFNCEXPORT OV_RESULT raspi_gpioOut_pin_set(
    OV_INSTPTR_raspi_gpioOut          pobj,
    const OV_INT  value
) {
    pobj->v_pin = value;
    OV_INSTPTR_raspi_gpioOut pinst = Ov_StaticPtrCast(raspi_gpioOut, pobj);
    pinst->v_initialized = FALSE;
    return OV_ERR_OK;
}


OV_DLLFNCEXPORT void raspi_gpioOut_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
	/* do what */
	OV_INSTPTR_raspi_gpioOut pinst = Ov_StaticPtrCast(raspi_gpioOut, pfb);

	if(!pinst->v_initialized){
		pinMode(pinst->v_pin, OUTPUT);
		pinst->v_initialized = TRUE;
	}
	digitalWrite(pinst->v_pin, pinst->v_input);
	pinst->v_error = 0;
	ov_string_setvalue(&pinst->v_errorMsg,"");
    return;
}

OV_DLLFNCEXPORT OV_RESULT raspi_gpioOut_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_raspi_gpioOut pinst = Ov_StaticPtrCast(raspi_gpioOut, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */
    wiringPiSetup();

    return OV_ERR_OK;
}

