
/******************************************************************************
*
*   FILE
*   ----
*   AAS.c
*
*   History
*   -------
*   2019-06-26   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_VWSiD
#define OV_COMPILE_LIBRARY_VWSiD
#endif


#include "VWSiD.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT VWSiD_AAS_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_VWSiD_AAS pinst = Ov_StaticPtrCast(VWSiD_AAS, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

