
/******************************************************************************
*
*   FILE
*   ----
*   Diagnosis.c
*
*   History
*   -------
*   2017-05-24   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openaas
#define OV_COMPILE_LIBRARY_openaas
#endif


#include "openaas.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openaas_Diagnosis_CallMethod(
  OV_INSTPTR_openaas_Service pobj,       
  OV_UINT numberofInputArgs,       
  const void **packedInputArgList,
  OV_UINT numberofOutputArgs,      
  void **packedOutputArgList,
  OV_UINT *typeArray
) {

	OV_INT inputs[3];
	inputs[0] = *(OV_UINT*)packedInputArgList[0];
	inputs[1] = *(OV_UINT*)packedInputArgList[1];
	inputs[2] = *(OV_UINT*)packedInputArgList[2];

	OV_INT abc = inputs[0] + inputs[1] + inputs[2];
	OV_UINT abc2 = inputs[1] - inputs[0];

	packedOutputArgList[0] = malloc(sizeof(OV_INT));
	packedOutputArgList[1] = malloc(sizeof(OV_UINT));

	*(OV_INT*)packedOutputArgList[0] = abc;
	typeArray[0] = OV_VT_INT;
	*(OV_INT*)packedOutputArgList[1] = abc2;
	typeArray[1] = OV_VT_UINT;

    return OV_ERR_OK;
}


