
/******************************************************************************
*
*   FILE
*   ----
*   library_open.c
*
*   History
*   -------
*   2017-08-01   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_propertyValueStatement
#define OV_COMPILE_LIBRARY_propertyValueStatement
#endif

#include "propertyValueStatement.h"
#ifdef ov_library_open_propertyValueStatement
#undef ov_library_open_propertyValueStatement
#endif

/*
* This function will be called, when the library is loaded.
* It could generate components and initializes the startup procedure
*/
OV_RESULT ov_library_setglobalvars_propertyValueStatement_new(void) {
	OV_RESULT result;
	/*
	 *    set the global variables of the original version
	 *    and if successful, load other libraries
	 *    and create some objects
	 */
	result = ov_library_setglobalvars_propertyValueStatement();
	return result;
}
/*
*       Replace the 'setglobalvars' function of a library with this
*       previous one, which additionally creates instances.
* 	This is called by the OV system upon library load.
*/
OV_DLLFNCEXPORT OV_LIBRARY_DEF *ov_library_open_propertyValueStatement(void) {
	/* local variables */
	static OV_LIBRARY_DEF *OV_LIBRARY_DEF_propertyValueStatement_new;
	/*
	*       replace the 'setglobalvars' function created by the code generator
	*       with a new one.
	*/
	OV_LIBRARY_DEF_propertyValueStatement_new = ov_library_open_propertyValueStatement_old();
	OV_LIBRARY_DEF_propertyValueStatement_new->setglobalvarsfnc = ov_library_setglobalvars_propertyValueStatement_new;
	return OV_LIBRARY_DEF_propertyValueStatement_new;
}
