#
# Makefile.bc -- toplevel makefile which can be used on NT to build
#                the C++ communication library.
#
# Copyright (c) 1996, 1997
# Chair of Process Control Engineering,
# Aachen University of Technology.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must print or display the above
#    copyright notice either during startup or must have a means for
#    the user to view the copyright notice.
# 3. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 4. Neither the name of the Chair of Process Control Engineering nor the
#    name of the Aachen University of Technology may be used to endorse or
#    promote products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE CHAIR OF PROCESS CONTROL ENGINEERING
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE CHAIR OF PROCESS CONTROL
# ENGINEERING BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# $Header: /home/david/cvs/acplt/makefile.nt,v 1.1 1997-04-29 13:18:15 harald Exp $
#

UNIXES	= linux hpux solaris
SOME_OTHER_OS = nt

nothing:
	@echo "Error! Usage:"
	@echo "make clean       -- remove all objects, executables, libraries, etc."
	@echo "make nt.all     -- build libraries and examples"
	@echo "make nt.acplt   -- build the libraries only"

clean:
	@echo "-------------------------------------------------------------"
	@echo "Cleaning up (can only do a minor clean, because we're on NT)"
	@echo "-------------------------------------------------------------"
	cd plt\build\nt
	make -f borland.mk clean
	cd ..\..\..
	cd ks\build\nt
	make -f borland.mk clean

nt.acplt:
	@echo "-------------------------------------------------------------"
	@echo "Building the libPLT..."
	@echo "-------------------------------------------------------------"
	cd plt\build\nt
	make -f borland.mk
	cd ..\..\..
	@echo "-------------------------------------------------------------"
	@echo "Building the libKS..."
	@echo "-------------------------------------------------------------"
	cd ks\build\nt
	make -f borland.mk
	cd ..\..\..

nt.all:	nt.acplt
	@echo "-------------------------------------------------------------"
	@echo "Building examples..."
	@echo "-------------------------------------------------------------"
	cd ks\build\nt
	make -f borland.mk examples
	cd ..\..\..

# End of Makefile.bc
