#ifndef _TLSF_VALGRIND_H_
#define _TLSF_VALGRIND_H_

#include "libov/tlsf.h"

#if OV_VALGRIND || 1
#include <valgrind/memcheck.h>
#define TLSF_VG_UNLOCK_BHDR(_b) VALGRIND_MAKE_MEM_DEFINED((_b), BHDR_OVERHEAD)
#define TLSF_VG_UNLOCK_FBLOCK(_b) VALGRIND_MAKE_MEM_DEFINED((_b), FREE_BLOCK_SIZE)
#define TLSF_VG_LOCK_BHDR(_b) VALGRIND_MAKE_MEM_NOACCESS((_b), BHDR_OVERHEAD)
#define TLSF_VG_LOCK_FBLOCK(_b) VALGRIND_MAKE_MEM_NOACCESS((_b), FREE_BLOCK_SIZE)
#else

#endif

#endif
