
/******************************************************************************
*
*   FILE
*   ----
*   ATAN.c
*
*   History
*   -------
*   2010-11-03   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec61131stdfb
#define OV_COMPILE_LIBRARY_iec61131stdfb
#endif

#define OV_DEBUG

#include "iec61131stdfb.h"
#include "stdfb_macros.h"
#include "libov/ov_macros.h"
#include "libov/ov_logfile.h"

#include <math.h>


OV_DLLFNCEXPORT OV_RESULT iec61131stdfb_ATAN_IN_set(
    OV_INSTPTR_iec61131stdfb_ATAN          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_IN, value);
}

OV_DLLFNCEXPORT OV_ANY* iec61131stdfb_ATAN_OUT_get(
    OV_INSTPTR_iec61131stdfb_ATAN          pobj
) {
    return &pobj->v_OUT;
}


OV_DLLFNCEXPORT void iec61131stdfb_ATAN_shutdown(OV_INSTPTR_ov_object pobj) {

	unsigned int i;
	
	OV_INSTPTR_iec61131stdfb_ATAN pinst = Ov_StaticPtrCast(iec61131stdfb_ATAN, pobj);
	
	STDFB_FREE_VEC(pinst->v_IN);
	STDFB_FREE_VEC(pinst->v_OUT);
	ov_object_shutdown(pobj);
}

OV_DLLFNCEXPORT void iec61131stdfb_ATAN_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
	
	unsigned int i;
	
    OV_INSTPTR_iec61131stdfb_ATAN pinst = Ov_StaticPtrCast(iec61131stdfb_ATAN, pfb);
	
	STDFB_FREE_VEC(pinst->v_OUT);
	if(!(pinst->v_IN.value.vartype & OV_VT_ISVECTOR))
		{
			switch(pinst->v_IN.value.vartype & OV_VT_KSMASK)
			{
				
				case OV_VT_INT:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					ov_logfile_warning("%s: tan of integer value, setting out to single to prevent data loss", pinst->v_identifier);
					pinst->v_OUT.value.valueunion.val_single = atan(pinst->v_IN.value.valueunion.val_int);
				break;
				
				case OV_VT_UINT:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					ov_logfile_warning("%s: tan of integer value, setting out to single to prevent data loss", pinst->v_identifier);
					pinst->v_OUT.value.valueunion.val_single = atan(pinst->v_IN.value.valueunion.val_uint); 
				break;
				
				case OV_VT_SINGLE:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					pinst->v_OUT.value.valueunion.val_single = atan(pinst->v_IN.value.valueunion.val_single);
				break;
				
				case OV_VT_DOUBLE:
					pinst->v_OUT.value.vartype = OV_VT_DOUBLE;
					pinst->v_OUT.value.valueunion.val_double = atan(pinst->v_IN.value.valueunion.val_double);
				
				break;

				case OV_VT_BYTE:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					pinst->v_OUT.value.valueunion.val_byte = atan(pinst->v_IN.value.valueunion.val_byte);
					ov_logfile_warning("%s: bitstring given, treating as unsigned integer, setting out to single to prevent data loss", pinst->v_identifier);
				break;
				
				
					
				default:
					pinst->v_OUT.value.vartype = OV_VT_BOOL;
					pinst->v_OUT.value.valueunion.val_bool = FALSE;
					ov_logfile_alert("%s: operation cannot be done on given datatype", pinst->v_identifier);
				break;
			}
		}
		else
		{
				switch(pinst->v_IN.value.vartype & OV_VT_KSMASK)
			{
			
				case OV_VT_INT_VEC:
					STDFB_VEC_ATAN_I(INT, int);
				break;
		
				case OV_VT_UINT_VEC:
					STDFB_VEC_ATAN_I(UINT, uint);
				break;
			
				case OV_VT_SINGLE_VEC:
					STDFB_VEC_ATAN_R(SINGLE, single);
				break;
		
				case OV_VT_DOUBLE_VEC:
					STDFB_VEC_ATAN_R(DOUBLE, double);
				break;

				case OV_VT_BYTE_VEC:
					ov_logfile_warning("%s: bitstring given, treating as unsigned integer", pinst->v_identifier);
					STDFB_VEC_ATAN_I(BYTE, byte);
				break;
			
				default:
					pinst->v_OUT.value.vartype = OV_VT_BOOL_VEC;
					Ov_SetDynamicVectorLength(&pinst->v_OUT.value.valueunion.val_bool_vec, 0, BOOL);
					ov_logfile_alert("%s: arctan of given datatypes senseless", pinst->v_identifier);
				break;
			}
		}
		
		/************** handling states ********************************/
		
	STDFB_STATE(IN);
	
	/***************** handling timestamps ************************/
	STDFB_TIMESTAMP(IN);
		
    return;
}

