
/******************************************************************************
*
*   FILE
*   ----
*   LT.c
*
*   History
*   -------
*   2010-11-30   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec61131stdfb
#define OV_COMPILE_LIBRARY_iec61131stdfb
#endif


#include "iec61131stdfb.h"
#include "stdfb_macros.h"
#include "libov/ov_macros.h"
#include "libov/ov_logfile.h"


OV_DLLFNCEXPORT OV_RESULT iec61131stdfb_LT_IN1_set(
    OV_INSTPTR_iec61131stdfb_LT          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_IN1, value);
}

OV_DLLFNCEXPORT OV_RESULT iec61131stdfb_LT_IN2_set(
    OV_INSTPTR_iec61131stdfb_LT          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_IN2, value);
}

OV_DLLFNCEXPORT OV_BOOL iec61131stdfb_LT_OUT_get(
    OV_INSTPTR_iec61131stdfb_LT          pobj
) {
    return pobj->v_OUT;
}


OV_DLLFNCEXPORT void iec61131stdfb_LT_shutdown(OV_INSTPTR_ov_object pobj) {

	unsigned int i;
	
	OV_INSTPTR_iec61131stdfb_LT pinst = Ov_StaticPtrCast(iec61131stdfb_LT, pobj);
	
	STDFB_FREE_VEC(pinst->v_IN1);
	STDFB_FREE_VEC(pinst->v_IN2);
	ov_object_shutdown(pobj);
}


OV_DLLFNCEXPORT void iec61131stdfb_LT_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_iec61131stdfb_LT pinst = Ov_StaticPtrCast(iec61131stdfb_LT, pfb);
	
	if((pinst->v_IN1.value.vartype & OV_VT_KSMASK) == (pinst->v_IN2.value.vartype & OV_VT_KSMASK))
	{
		if(!(pinst->v_IN1.value.vartype & OV_VT_ISVECTOR))
		{
			switch(pinst->v_IN1.value.vartype & OV_VT_KSMASK)
			{
				STDFB_LT(BOOL, bool);
				STDFB_LT(BYTE, byte);
				STDFB_LT(UINT, uint);
				STDFB_LT(INT, int);
				STDFB_LT(SINGLE, single);
				STDFB_LT(DOUBLE, double);
				
				case OV_VT_STRING:
					if(ov_string_compare(pinst->v_IN1.value.valueunion.val_string, pinst->v_IN2.value.valueunion.val_string) < 0)
						pinst->v_OUT = TRUE;
					else
						pinst->v_OUT = FALSE;
				break;
				
				case OV_VT_TIME:
					if(STDFB_LT_TIME(pinst->v_IN1.value.valueunion.val_time, pinst->v_IN2.value.valueunion.val_time))
						pinst->v_OUT = TRUE;
					else
						pinst->v_OUT = FALSE;
						
				break;
				
				case OV_VT_TIME_SPAN:
					if(STDFB_LT_TIME(pinst->v_IN1.value.valueunion.val_time_span, pinst->v_IN2.value.valueunion.val_time_span))
						pinst->v_OUT = TRUE;
					else
						pinst->v_OUT = FALSE;
				break;
				
				default:
					ov_logfile_error("%s: comparison of given datatype not implementes", pinst->v_identifier);
					pinst->v_OUT = FALSE;
					return;
			}
		}
		else
		{
			ov_logfile_warning("%s: comparison of vectors concerns their length only", pinst->v_identifier);
			switch(pinst->v_IN1.value.vartype & OV_VT_KSMASK)
			{
				STDFB_LT_VEC(BOOL, bool);
				STDFB_LT_VEC(BYTE, byte);
				STDFB_LT_VEC(UINT, uint);
				STDFB_LT_VEC(INT, int);
				STDFB_LT_VEC(SINGLE, single);
				STDFB_LT_VEC(DOUBLE, double);
				STDFB_LT_VEC(STRING, string);
				STDFB_LT_VEC(TIME, time);
				STDFB_LT_VEC(TIME_SPAN, time_span);
				
				default:
						ov_logfile_error("%s: comparison of given datatype not implementes", pinst->v_identifier);
						pinst->v_OUT = FALSE;
						return;
			}
		}
		



	}
	else
	{
		ov_logfile_error("%s: trying to use inputs of different type on LT-block", pinst->v_identifier);
		pinst->v_OUT = 0;
		return;
	}
	
    return;
}

