
/******************************************************************************
*
*   FILE
*   ----
*   SQRT.c
*
*   History
*   -------
*   2010-11-03   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_iec61131stdfb
#define OV_COMPILE_LIBRARY_iec61131stdfb
#endif

#define OV_DEBUG

#include "iec61131stdfb.h"
#include "stdfb_macros.h"
#include "libov/ov_macros.h"
#include "libov/ov_logfile.h"

#include <math.h>


OV_DLLFNCEXPORT OV_RESULT iec61131stdfb_SQRT_IN_set(
    OV_INSTPTR_iec61131stdfb_SQRT          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_IN, value);
}

OV_DLLFNCEXPORT OV_ANY* iec61131stdfb_SQRT_OUT_get(
    OV_INSTPTR_iec61131stdfb_SQRT          pobj
) {
    return &pobj->v_OUT;
}

OV_DLLFNCEXPORT void iec61131stdfb_SQRT_shutdown(OV_INSTPTR_ov_object pobj) {

	unsigned int i;
	
	OV_INSTPTR_iec61131stdfb_SQRT pinst = Ov_StaticPtrCast(iec61131stdfb_SQRT, pobj);
	
	STDFB_FREE_VEC(pinst->v_IN);
	STDFB_FREE_VEC(pinst->v_OUT);
	ov_object_shutdown(pobj);
}


OV_DLLFNCEXPORT void iec61131stdfb_SQRT_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
	unsigned int i;
	
    OV_INSTPTR_iec61131stdfb_SQRT pinst = Ov_StaticPtrCast(iec61131stdfb_SQRT, pfb);
	STDFB_FREE_VEC(pinst->v_OUT);
	if(!(pinst->v_IN.value.vartype & OV_VT_ISVECTOR))
		{
			switch(pinst->v_IN.value.vartype & OV_VT_KSMASK)
			{
				
				case OV_VT_INT:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					ov_logfile_warning("%s: input value is integer, output is set to single to prevent data loss", pinst->v_identifier);
					if(pinst->v_IN.value.valueunion.val_int < 0)
					{
						pinst->v_OUT.value.valueunion.val_int = 0;
						ov_logfile_error("%s: trying to calculate the squareroot of a negative value", pinst->v_identifier);
						
					}
					else
						pinst->v_OUT.value.valueunion.val_single = sqrt(pinst->v_IN.value.valueunion.val_int);
				break;
				
				case OV_VT_UINT:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					pinst->v_OUT.value.valueunion.val_single = sqrt(pinst->v_IN.value.valueunion.val_uint);
					ov_logfile_warning("%s: input value is integer, output is set to single to prevent data loss", pinst->v_identifier);
				break;
				
				case OV_VT_SINGLE:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					if(pinst->v_IN.value.valueunion.val_single < 0)
					{
						pinst->v_OUT.value.valueunion.val_single = 0;
						ov_logfile_error("%s: trying to calculate the squareroot of a negative value", pinst->v_identifier);
					}
					else
						pinst->v_OUT.value.valueunion.val_single = sqrt(pinst->v_IN.value.valueunion.val_single);
				break;
				
				case OV_VT_DOUBLE:
					pinst->v_OUT.value.vartype = OV_VT_DOUBLE;
					if(pinst->v_IN.value.valueunion.val_double < 0)
					{
						pinst->v_OUT.value.valueunion.val_double = 0;
						ov_logfile_error("%s: trying to calculate the squareroot of a negative value", pinst->v_identifier);
					}
					else
						pinst->v_OUT.value.valueunion.val_double = sqrt(pinst->v_IN.value.valueunion.val_double);
				
				break;
				
				case OV_VT_BYTE:
					pinst->v_OUT.value.vartype = OV_VT_SINGLE;
					pinst->v_OUT.value.valueunion.val_single = sqrt(pinst->v_IN.value.valueunion.val_byte);
					ov_logfile_warning("%s: input value is integer, output is set to single to prevent data loss", pinst->v_identifier);
				break;

				default:
					pinst->v_OUT.value.vartype = OV_VT_BOOL;
					pinst->v_OUT.value.valueunion.val_bool = FALSE;
					ov_logfile_alert("%s: operation cannot be done on given datatype", pinst->v_identifier);
				break;
			}
		}
		else
		{
			switch(pinst->v_IN.value.vartype & OV_VT_KSMASK)
			{
			
				case OV_VT_INT_VEC:
					STDFB_VEC_SQRT_I(INT, int);
				break;
			
				case OV_VT_UINT_VEC:
					STDFB_VEC_SQRT_I(UINT, uint);
				break;
				
				case OV_VT_SINGLE_VEC:
					STDFB_VEC_SQRT_R(SINGLE, single);
				break;
			
				case OV_VT_DOUBLE_VEC:
					STDFB_VEC_SQRT_R(DOUBLE, double);
				break;

				case OV_VT_BYTE_VEC:
					STDFB_VEC_SQRT_I(BYTE, byte);
				break;
			
				default:
					pinst->v_OUT.value.vartype = OV_VT_BOOL_VEC;
					Ov_SetDynamicVectorLength(&pinst->v_OUT.value.valueunion.val_bool_vec, 0, BOOL);
					ov_logfile_alert("%s: sqrt of given datatypes senseless", pinst->v_identifier);
				break;
			}
		}
		
	/****************** handling states nad timestamp ******************/
	STDFB_STATE(IN);
	STDFB_TIMESTAMP(IN);
		
    return;
}

