/*
*   The Framework was generated by the ACPLT/OV Builder.
*
*   Builder version: 1.0.4
*   Date of file generation:  15-Jul-2011 (13:34:12)
*/

#ifndef OV_COMPILE_LIBRARY_ssc
#define OV_COMPILE_LIBRARY_ssc
#endif


#include "ssc.h"
#include "ssclib.h"


OV_DLLFNCEXPORT OV_RESULT ssc_setVariable_variable_set(
    OV_INSTPTR_ssc_setVariable          pinst,
    const OV_STRING  value
) {
    // check input
    if (ov_string_compare(value, NULL)==0)
    {
    	pinst->v_error=TRUE;
       	ov_string_setvalue(&pinst->v_errorDetail, "variable is not defined.");
       	return OV_ERR_OK;
    };

    pinst->v_error=FALSE;
    ov_string_setvalue(&pinst->v_errorDetail, NULL);

    return ov_string_setvalue(&pinst->v_variable,value);
}

OV_DLLFNCEXPORT OV_RESULT ssc_setVariable_value_set(
    OV_INSTPTR_ssc_setVariable          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_value, value);
}

OV_DLLFNCEXPORT void ssc_setVariable_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    // local variables
    OV_INSTPTR_ssc_setVariable pinst = Ov_StaticPtrCast(ssc_setVariable, pfb);
    OV_INSTPTR_ssc_step  pStep= Ov_DynamicPtrCast(ssc_step, Ov_GetParent(ov_containment, pinst));
    OV_INSTPTR_ssc_sscHeader  pSSC= Ov_DynamicPtrCast(ssc_sscHeader, Ov_GetParent(ov_containment, pStep));
    OV_RESULT    result;

    // init variables
    pinst->v_cyctime.secs = 0;
    pinst->v_cyctime.usecs = 0;
    pinst->v_iexreq = 1;
    pinst->v_error=FALSE;
    ov_string_setvalue(&pinst->v_errorDetail, NULL);

    // check location
    if ( pStep==NULL )
	{
    	pinst->v_error=TRUE;
		ov_logfile_error("ssc_actionBlock_constructor: action block must be encapsulated in a step.");
		return;
	}

    // check input
    if (ov_string_compare(pinst->v_variable, NULL)==0)
    {
    	pinst->v_error=TRUE;
       	ov_string_setvalue(&pinst->v_errorDetail, "variable is not defined.");
    };

    // set variable
    //result= fb_functionchart_getvariable(Ov_PtrUpCast(fb_functionchart, pSSC), pinst->v_variable, &pinst->v_value);
    //result= fb_functionchart_setvariable(Ov_PtrUpCast(fb_functionchart, pSSC), pinst->v_variable, &pinst->v_value);

    result= fb_functionchart_setport( Ov_DynamicPtrCast(fb_functionchart, Ov_GetParent(ov_containment, pSSC)), pinst->v_variable, &pinst->v_value);
    if(Ov_Fail(result))
    {
    	pinst->v_error=TRUE;
    	ov_string_setvalue(&pinst->v_errorDetail, "bad parameter");

    }

    /*
    		OV_INSTPTR_fb_functionchart pfc,
    		 const OV_STRING varname,
    		 OV_ANY *pvarcurrprops)
*/

    return;
}

OV_DLLFNCEXPORT OV_RESULT ssc_setVariable_setActionName(
             OV_INSTPTR_ssc_actionBlock          pinst,
             const OV_STRING  value
) {
	return ov_string_setvalue(&pinst->v_actionName,value);
}
