
/******************************************************************************
*
*   FILE
*   ----
*   sourcevariable.c
*
*   History
*   -------
*   2011-06-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'fb_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_fb
#define OV_COMPILE_LIBRARY_fb
#endif


#include "fb.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(fb_sourcevariable)
//OV_IMPL_UNLINK(fb_sourcevariable)
OV_IMPL_GETACCESS(fb_sourcevariable)

OV_DLLFNCEXPORT void
fb_sourcevariable_unlink
(const OV_PPT_fb_sourcevariable pparent,
 const OV_CPT_fb_sourcevariable pchild)
{
  OV_INSTPTR_fb_connection pconn =
    Ov_StaticPtrCast (fb_connection, pchild);
  
  if( (!pparent) || (!pchild) ) {
    return;
  }
  
  /* Deactivate connection */
  pconn->v_on = FALSE;
  pconn->v_sourceelem.elemtype = OV_ET_NONE;
  pconn->v_targetelem.elemtype = OV_ET_NONE;
  
  /* Unlink */
  ov_association_unlink (passoc_fb_sourcevariable,
                         Ov_PtrUpCast (ov_object, pparent),
                         Ov_PtrUpCast (ov_object, pchild));
}
