
/******************************************************************************
*
*   FILE
*   ----
*   SEWrapper.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_storeData(OV_INSTPTR_openAASDiscoveryServer_SEWrapper this) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_searchData(OV_INSTPTR_openAASDiscoveryServer_SEWrapper this){

    return OV_ERR_OK;
}

