/******************************************************************************
 *
 *   FILE
 *   ----
 *   helpers.c
 *
 *   History
 *   -------
 *   2014-10-21   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_servicesOPCUAInterface
#define OV_COMPILE_LIBRARY_servicesOPCUAInterface
#endif

#include "servicesOPCUAInterface.h"
#include "libov/ov_macros.h"
#include "opcua.h"
#include "opcua_helpers.h"
#include "opcua_ovStore.h"

OV_DLLFNCEXPORT UA_StatusCode servicesOPCUAInterface_interface_ovServiceNodeToOPCUA(
		void *context, const UA_NodeId *nodeId, UA_Node** opcuaNode) {
	UA_Node 				*newNode = NULL;
	UA_StatusCode 			result = UA_STATUSCODE_GOOD;
	OV_PATH 				path;
	OV_INSTPTR_ov_object	pobj = NULL;
	OV_TICKET 				*pTicket = NULL;
	OV_VTBLPTR_ov_object	pVtblObj = NULL;
	OV_ACCESS				access;
	UA_NodeClass 			nodeClass;
	OV_ELEMENT				element;
	OV_INSTPTR_servicesOPCUAInterface_interface 	pinterface = Ov_StaticPtrCast(servicesOPCUAInterface_interface, context);

	ov_memstack_lock();
	result = opcua_helpers_resolveNodeIdToPath(*nodeId, &path);
	if(result != UA_STATUSCODE_GOOD){
		ov_memstack_unlock();
		return result;
	}
	element = path.elements[path.size-1];
	ov_memstack_unlock();
	result = opcua_helpers_getVtblPointerAndCheckAccess(&(element), pTicket, &pobj, &pVtblObj, &access);
	if(result != UA_STATUSCODE_GOOD){
		return result;
	}

	nodeClass = UA_NODECLASS_METHOD;
	newNode = (UA_Node*)UA_calloc(1, sizeof(UA_MethodNode));

	// Basic Attribute
	// BrowseName
	UA_QualifiedName qName;
	qName.name = UA_String_fromChars(pobj->v_identifier);
	qName.namespaceIndex = nodeId->namespaceIndex;
	newNode->browseName = qName;

	// Description
	OV_STRING tempString = pVtblObj->m_getcomment(pobj, &element);
	UA_LocalizedText lText;
	UA_LocalizedText_init(&lText);
	lText.locale = UA_String_fromChars("en");
	if(tempString){
		lText.text = UA_String_fromChars(tempString);
	} else {
		lText.text = UA_String_fromChars("");
	}
	UA_LocalizedText_copy(&lText,&newNode->description);
	UA_LocalizedText_deleteMembers(&lText);

	// DisplayName
	UA_LocalizedText displayName;
	UA_LocalizedText_init(&displayName);
	displayName.locale = UA_String_fromChars("en");
	displayName.text = UA_String_fromChars(pobj->v_identifier);
	UA_LocalizedText_copy(&displayName, &newNode->displayName);
	UA_LocalizedText_deleteMembers(&displayName);

	// NodeId
	UA_NodeId_copy(nodeId, &newNode->nodeId);

	// NodeClass
	newNode->nodeClass 	= nodeClass;

	// WriteMask
	UA_UInt32 writeMask = 0;
	if(element.elemtype != OV_ET_VARIABLE){
		if(access & OV_AC_WRITE){
			writeMask |= (1<<2);	//	BrowseName
			writeMask |= (1<<6);	//	DisplayName
		}
		if(access & OV_AC_RENAMEABLE){
			writeMask |= (1<<14);	//	NodeId
		}
	}
	newNode->writeMask 	= writeMask;

	((UA_ObjectNode*)newNode)->eventNotifier = 0;

	((UA_MethodNode*)newNode)->executable = TRUE;
	((UA_MethodNode*)newNode)->method = servicesOPCUAInterface_interface_MethodCallback;
	((UA_MethodNode*)newNode)->context = pobj;

	// References
	opcua_ovStore_addReference(context, newNode);
	UA_NodeId tmpNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_HASTYPEDEFINITION);
	UA_String Revision = UA_STRING_NULL;
	UA_String_copy(&nodeId->identifier.string, &Revision);
	opcua_helpers_UA_String_append(&Revision,".ServiceRevision");
	UA_String Version = UA_STRING_NULL;
	UA_String_copy(&nodeId->identifier.string, &Version);
	opcua_helpers_UA_String_append(&Version,".ServiceVersion");
	UA_String WSDL = UA_STRING_NULL;
	UA_String_copy(&nodeId->identifier.string, &WSDL);
	opcua_helpers_UA_String_append(&WSDL,".WSDL");

	for (size_t i = 0; i < newNode->referencesSize; i++){
		if (UA_NodeId_equal(&newNode->references[i].referenceTypeId, &tmpNodeId)){
			newNode->references[i].targetIds[0] = UA_EXPANDEDNODEID_NUMERIC(0, UA_NS0ID_METHODNODE);
			continue;
		}
		for (size_t j = 0; j < newNode->references[i].targetIdsSize ; j++){
			if (UA_String_equal(&Revision, &newNode->references[i].targetIds[j].nodeId.identifier.string) ||
				UA_String_equal(&Version, &newNode->references[i].targetIds[j].nodeId.identifier.string) ||
				UA_String_equal(&WSDL, &newNode->references[i].targetIds[j].nodeId.identifier.string)){
				newNode->references[i].targetIds[j].nodeId.namespaceIndex = pinterface->v_trafo->index;
			}
		}
	}
	UA_String_deleteMembers(&Revision);
	UA_String_deleteMembers(&Version);
	UA_String_deleteMembers(&WSDL);
	UA_NodeId_deleteMembers(&tmpNodeId);

	// InputArguments
	OV_STRING tmpString = NULL;
	opcua_helpers_copyUAStringToOV(nodeId->identifier.string, &tmpString);
	ov_string_append(&tmpString, "||");
	ov_string_append(&tmpString, "InputArguments");
	opcua_helpers_addReference(newNode, NULL, UA_NODEID_NUMERIC(0, UA_NS0ID_HASPROPERTY),
			UA_EXPANDEDNODEID_STRING_ALLOC(pinterface->v_trafo->index, tmpString), UA_NODECLASS_VARIABLE,
			UA_TRUE);
	ov_string_setvalue(&tmpString, NULL);

	// OutputArguments
	tmpString = NULL;
	opcua_helpers_copyUAStringToOV(nodeId->identifier.string, &tmpString);
	ov_string_append(&tmpString, "||");
	ov_string_append(&tmpString, "OutputArguments");
	opcua_helpers_addReference(newNode, NULL, UA_NODEID_NUMERIC(0, UA_NS0ID_HASPROPERTY),
			UA_EXPANDEDNODEID_STRING_ALLOC(pinterface->v_trafo->index, tmpString), UA_NODECLASS_VARIABLE,
			UA_TRUE);
	ov_string_setvalue(&tmpString, NULL);

	// HasComponent to parent
	OV_INSTPTR_ov_object pParent = Ov_StaticPtrCast(ov_object, Ov_GetParent(ov_containment, pobj));
	opcua_helpers_addReference(newNode, NULL, UA_NODEID_NUMERIC(0, UA_NS0ID_HASCOMPONENT),
			UA_EXPANDEDNODEID_STRING_ALLOC(opcua_ovStore_searchNamespaceIndex(context, pParent, FALSE),
					ov_path_getcanonicalpath(pParent, 2)),
			UA_NODECLASS_OBJECT, UA_FALSE);

	ov_string_setvalue(&tmpString, NULL);
	*opcuaNode = newNode;
	return UA_STATUSCODE_GOOD;
}

