
/******************************************************************************
*
*   FILE
*   ----
*   arguments.c
*
*   History
*   -------
*   2016-06-15   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_opcua
#define OV_COMPILE_LIBRARY_opcua
#endif


#include "opcua.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING* opcua_arguments_Names_get(
    OV_INSTPTR_opcua_arguments          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_Names.veclen;
    return pobj->v_Names.value;
}

OV_DLLFNCEXPORT OV_INT* opcua_arguments_Types_get(
    OV_INSTPTR_opcua_arguments          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_Types.veclen;
    return pobj->v_Types.value;
}

OV_DLLFNCEXPORT OV_BOOL* opcua_arguments_isArray_get(
    OV_INSTPTR_opcua_arguments          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_isArray.veclen;
    return pobj->v_isArray.value;
}

OV_DLLFNCEXPORT OV_UINT* opcua_arguments_Lengths_get(
    OV_INSTPTR_opcua_arguments          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_Lengths.veclen;
    return pobj->v_Lengths.value;
}

OV_DLLFNCEXPORT OV_STRING* opcua_arguments_Descriptions_get(
    OV_INSTPTR_opcua_arguments          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_Descriptions.veclen;
    return pobj->v_Descriptions.value;
}

OV_DLLFNCEXPORT OV_ACCESS opcua_arguments_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
	//OV_INSTPTR_opcua_arguments pinst = Ov_StaticPtrCast(opcua_arguments, pobj);
	switch(pelem->elemtype) {
	case OV_ET_VARIABLE:	/*	we only have readOnly variables	*/
		if(pelem->elemunion.pvar->v_offset >= offsetof(OV_INST_ov_object,__classinfo) ) {
			if(pelem->elemunion.pvar->v_vartype == OV_VT_CTYPE)
				return OV_AC_NONE;
			else
				return OV_AC_READ;
		} else {
			return ov_object_getaccess(pobj, pelem, pticket);
		}
		break;
	default:
		break;
	}
	return ov_object_getaccess(pobj, pelem, pticket);
}

OV_DLLFNCEXPORT OV_RESULT opcua_arguments_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*
    *   local variables
    */
    OV_INSTPTR_opcua_arguments pinst = Ov_StaticPtrCast(opcua_arguments, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */
    if(!pinst->v_pouterobject){
    	return OV_ERR_BADPLACEMENT;
    }
    if(!Ov_CanCastTo(opcua_methodNode, pinst->v_pouterobject)){
    	return OV_ERR_BADPLACEMENT;
    }
    return OV_ERR_OK;
}

