
/******************************************************************************
*
*   FILE
*   ----
*   uaInterface.c
*
*   History
*   -------
*   2019-01-18   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_opcua
#define OV_COMPILE_LIBRARY_opcua
#endif


#include "opcua.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_ACCESS opcua_uaInterface_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
//    OV_INSTPTR_opcua_uaInterface pinst = Ov_StaticPtrCast(opcua_uaInterface, pobj);

    return (OV_ACCESS)0;
}

OV_DLLFNCEXPORT OV_RESULT opcua_uaInterface_load(void){

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT opcua_uaInterface_unload(void){

    return OV_ERR_OK;
}

