/* WARNING: This is a generated file.
 * Any manual changes will be overwritten. */

#ifndef PROPERTYVALUESTATEMENT_H_
#define PROPERTYVALUESTATEMENT_H_

# include "open62541.h"

#define UA_NSPROPERTYVALUESTATEMENTID_EXPRESSIONLOGICENUM 3002
#define UA_NSPROPERTYVALUESTATEMENTID_EXPRESSIONSEMANTICENUM 3003
#define UA_NSPROPERTYVALUESTATEMENTID_VIEWENUM 3004
#define UA_NSPROPERTYVALUESTATEMENTID_VISIBILITYENUM 3005
#define UA_NSPROPERTYVALUESTATEMENTID_PROPERTYVALUESTATEMENTTYPE 2002
#define UA_NSPROPERTYVALUESTATEMENTID_PROPERTYVALUESTATEMENTLISTTYPE 1002

_UA_BEGIN_DECLS

extern UA_StatusCode nodeset_propertyValueStatement(UA_Server *server);

_UA_END_DECLS

#endif /* PROPERTYVALUESTATEMENT_H_ */
