
/******************************************************************************
*
*   FILE
*   ----
*   TCPChannel.c
*
*   History
*   -------
*   2013-01-17   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_TCPbind
#define OV_COMPILE_LIBRARY_TCPbind
#endif


#include "TCPbind.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_INT TCPbind_TCPChannel_socket_get(
    OV_INSTPTR_TCPbind_TCPChannel          pobj
) {
    return pobj->v_socket;
}

OV_DLLFNCEXPORT OV_RESULT TCPbind_TCPChannel_socket_set(
    OV_INSTPTR_TCPbind_TCPChannel          pobj,
    const OV_INT  value
) {
    pobj->v_socket = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT TCPbind_TCPChannel_SendData(
	OV_INSTPTR_ksbase_Channel this
) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void TCPbind_TCPChannel_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_TCPbind_TCPChannel pinst = Ov_StaticPtrCast(TCPbind_TCPChannel, pobj);

    /* do what the base class does first */
    ov_object_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void TCPbind_TCPChannel_shutdown(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_TCPbind_TCPChannel pinst = Ov_StaticPtrCast(TCPbind_TCPChannel, pobj);

    /* do what */

    /* set the object's state to "shut down" */
    ksbase_Channel_shutdown(pobj);

    return;
}

OV_DLLFNCEXPORT void TCPbind_TCPChannel_typemethod (
	OV_INSTPTR_ksbase_ComTask	this
) {
    /*    
    *   local variables
    */

    return;
}

OV_DLLFNCEXPORT OV_RESULT TCPbind_TCPChannel_OpenConnection(
	OV_INSTPTR_TCPbind_TCPChannel this,
	OV_STRING host,
	OV_INT port,
	OV_INT* socket
) {

	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT TCPbind_TCPChannel_AssociateClientHandler(
	OV_INSTPTR_TCPbind_TCPChannel this
) {
    return OV_ERR_OK;
}

